version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    networks:
      - nesjs-network
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: gosmas-test
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  nesjs-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
